using Microsoft.EntityFrameworkCore;
using Mazaya.Rga.Api.Models;

namespace Mazaya.Rga.Api.Data;

public class RgaDbContext : DbContext
{
    public RgaDbContext(DbContextOptions<RgaDbContext> options) : base(options) { }

    public DbSet<User> Users => Set<User>();
    public DbSet<Customer> Customers => Set<Customer>();
    public DbSet<Project> Projects => Set<Project>();
    public DbSet<QuestionnaireResponse> QuestionnaireResponses => Set<QuestionnaireResponse>();
    public DbSet<DataItem> DataItems => Set<DataItem>();
    public DbSet<Session> Sessions => Set<Session>();
    public DbSet<Mom> Moms => Set<Mom>();
    public DbSet<Escalation> Escalations => Set<Escalation>();
    public DbSet<Risk> Risks => Set<Risk>();
    public DbSet<Issue> Issues => Set<Issue>();
    public DbSet<ChangeRequest> ChangeRequests => Set<ChangeRequest>();
    public DbSet<ChangeRequestApproval> ChangeRequestApprovals => Set<ChangeRequestApproval>();
    public DbSet<O365Credential> O365Credentials => Set<O365Credential>();
    public DbSet<StateDocument> StateDocuments => Set<StateDocument>();
    public DbSet<CustomerDomain> CustomerDomains => Set<CustomerDomain>();

    protected override void OnModelCreating(ModelBuilder b)
    {
        // Map to the snake_case tables created by the SQL migrations.
        b.Entity<User>().ToTable("users");
        b.Entity<Customer>().ToTable("customers");
        b.Entity<Project>().ToTable("projects");
        b.Entity<QuestionnaireResponse>().ToTable("questionnaire_responses");
        b.Entity<DataItem>().ToTable("data_items");
        b.Entity<Session>().ToTable("sessions");
        b.Entity<Mom>().ToTable("moms");
        b.Entity<Escalation>().ToTable("escalations");
        b.Entity<Risk>().ToTable("risks");
        b.Entity<Issue>().ToTable("issues");
        b.Entity<ChangeRequest>().ToTable("change_requests");
        b.Entity<ChangeRequestApproval>().ToTable("change_request_approvals");
        b.Entity<O365Credential>().ToTable("o365_credentials");
        b.Entity<StateDocument>().ToTable("state_documents").HasKey(s => s.Key);
        b.Entity<CustomerDomain>().ToTable("customer_domains");

        // Lower-case every column name not already mapped via [Column].
        foreach (var entity in b.Model.GetEntityTypes())
            foreach (var prop in entity.GetProperties())
                if (prop.GetColumnName() == prop.Name)        // not explicitly mapped
                    prop.SetColumnName(ToSnake(prop.Name));

        // DB-computed columns (generated by the SQL migrations) — EF reads them
        // but must never insert or update them.
        b.Entity<Risk>().Property(r => r.Severity)
            .ValueGeneratedOnAddOrUpdate()
            .Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
        b.Entity<Risk>().Property(r => r.Severity)
            .Metadata.SetBeforeSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
        b.Entity<ChangeRequest>().Property(c => c.NeedsSteering)
            .ValueGeneratedOnAddOrUpdate()
            .Metadata.SetAfterSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);
        b.Entity<ChangeRequest>().Property(c => c.NeedsSteering)
            .Metadata.SetBeforeSaveBehavior(Microsoft.EntityFrameworkCore.Metadata.PropertySaveBehavior.Ignore);

        // Relationships
        b.Entity<Project>().HasMany(p => p.Questionnaire).WithOne().HasForeignKey(q => q.ProjectId);
        b.Entity<Project>().HasMany(p => p.DataItems).WithOne().HasForeignKey(d => d.ProjectId);
        b.Entity<Project>().HasMany(p => p.Sessions).WithOne().HasForeignKey(s => s.ProjectId);
        b.Entity<Project>().HasMany(p => p.Moms).WithOne().HasForeignKey(m => m.ProjectId);
        b.Entity<Project>().HasMany(p => p.Escalations).WithOne().HasForeignKey(e => e.ProjectId);
        b.Entity<Project>().HasMany(p => p.Risks).WithOne().HasForeignKey(r => r.ProjectId);
        b.Entity<Project>().HasMany(p => p.Issues).WithOne().HasForeignKey(i => i.ProjectId);
        b.Entity<Project>().HasMany(p => p.ChangeRequests).WithOne().HasForeignKey(c => c.ProjectId);
        b.Entity<Customer>().HasMany(c => c.Projects).WithOne().HasForeignKey(p => p.CustomerId);
        b.Entity<ChangeRequest>().HasMany(c => c.Approvals).WithOne().HasForeignKey(a => a.CrId);
    }

    private static string ToSnake(string name)
    {
        var sb = new System.Text.StringBuilder();
        for (int i = 0; i < name.Length; i++)
        {
            if (char.IsUpper(name[i]) && i > 0) sb.Append('_');
            sb.Append(char.ToLowerInvariant(name[i]));
        }
        return sb.ToString();
    }
}
